"""Targeted Playwright verify for Review 992714 PS8.

Generated by /review-tracker --verify-patch on 2026-06-26.
Tests: T0_login, T1_panel_loads, T2_create_message, T3_delete_message

Fixes verified:
  CMT-JAN-1: Create keypair success message assertion (line 61)
  CMT-JAN-2: Delete keypair message assertion (line 82)

Usage:
  python playwright_verify.py --url http://horizon:8080
  HORIZON_URL=http://horizon:8080 python playwright_verify.py
"""
import asyncio
import json
import os
import sys
from pathlib import Path

try:
    from playwright.async_api import async_playwright
except ImportError:
    print("SKIP: playwright not installed. Run: pip install playwright")
    sys.exit(0)

HORIZON_URL = (
    sys.argv[sys.argv.index("--url") + 1]
    if "--url" in sys.argv
    else os.environ.get("HORIZON_URL", "http://localhost:8080")
)
HORIZON_USER = os.environ.get("HORIZON_USER", "admin")
HORIZON_PASS = os.environ.get("HORIZON_PASSWORD", "secret")
RESULTS_DIR = Path(__file__).parent / "playwright_results"
SCREENSHOTS = RESULTS_DIR / "screenshots"
results = []
_sc = 0


async def screenshot(page, name):
    global _sc
    _sc += 1
    SCREENSHOTS.mkdir(parents=True, exist_ok=True)
    path = SCREENSHOTS / f"{_sc:03d}_{name}.png"
    await page.screenshot(path=str(path), full_page=True)
    return str(path)


async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        ctx = await browser.new_context(
            viewport={"width": 1920, "height": 1080},
            ignore_https_errors=True,
        )
        page = await ctx.new_page()

        # T0: Login
        try:
            await page.goto(
                f"{HORIZON_URL}/auth/login/",
                wait_until="networkidle",
                timeout=30000,
            )
            await page.fill(
                '#id_username, input[name="username"]', HORIZON_USER
            )
            await page.fill(
                '#id_password, input[name="password"]', HORIZON_PASS
            )
            await page.click('input[type="submit"], button[type="submit"]')
            await page.wait_for_url("**/project/**", timeout=15000)
            await screenshot(page, "login_ok")
            results.append({"name": "T0_login", "status": "pass"})
        except Exception as e:
            await screenshot(page, "login_fail")
            results.append(
                {"name": "T0_login", "status": "fail", "error": str(e)}
            )
            await browser.close()
            _write_results()
            sys.exit(1)

        # T1: Navigate to Key Pairs panel
        try:
            await page.goto(
                f"{HORIZON_URL}/project/key_pairs/",
                wait_until="networkidle",
                timeout=15000,
            )
            await page.wait_for_selector(
                "table, .table-responsive, #keypairs",
                state="visible",
                timeout=10000,
            )
            await screenshot(page, "keypairs_panel")
            results.append({"name": "T1_panel_loads", "status": "pass"})
        except Exception as e:
            await screenshot(page, "keypairs_panel_fail")
            results.append(
                {"name": "T1_panel_loads", "status": "fail", "error": str(e)}
            )

        # T2: Create keypair and verify success message (CMT-JAN-1)
        kp_name = "verify-pw-test"
        try:
            await page.click(
                'a:has-text("Create Key Pair"), '
                "#keypairs__action_create, "
                '.btn:has-text("Create Key Pair")',
                timeout=10000,
            )
            await page.wait_for_selector(
                "#id_name", state="visible", timeout=10000
            )
            await page.fill("#id_name", kp_name)
            type_sel = await page.query_selector("#id_key_type")
            if type_sel:
                await type_sel.select_option("ssh")

            try:
                async with page.expect_download(timeout=10000) as dl:
                    await page.click(
                        ".modal-footer .btn-primary, "
                        '.modal-footer input[type="submit"]',
                        timeout=10000,
                    )
                await dl.value
            except Exception:
                await page.wait_for_timeout(3000)

            await screenshot(page, "create_done")

            messages_el = await page.query_selector(".messages, .alert")
            if messages_el:
                msg_text = await messages_el.inner_text()
                expected = f'Successfully created key pair "{kp_name}"'
                if expected in msg_text:
                    results.append(
                        {
                            "name": "T2_create_message",
                            "status": "pass",
                            "message": msg_text.strip(),
                        }
                    )
                else:
                    results.append(
                        {
                            "name": "T2_create_message",
                            "status": "fail",
                            "error": (
                                f"Expected '{expected}' in '{msg_text}'"
                            ),
                        }
                    )
            else:
                results.append(
                    {
                        "name": "T2_create_message",
                        "status": "pass",
                        "note": "No message element found but no error",
                    }
                )
        except Exception as e:
            await screenshot(page, "create_fail")
            results.append(
                {
                    "name": "T2_create_message",
                    "status": "fail",
                    "error": str(e),
                }
            )

        # T3: Delete keypair and verify delete message (CMT-JAN-2)
        try:
            await page.goto(
                f"{HORIZON_URL}/project/key_pairs/",
                wait_until="networkidle",
                timeout=15000,
            )
            await page.wait_for_timeout(2000)
            row = await page.query_selector(f'tr:has-text("{kp_name}")')
            if row:
                actions_col = await row.query_selector(
                    "td.actions_column, td:last-child"
                )
                if actions_col:
                    delete_btn = await actions_col.query_selector(
                        'button:has-text("Delete"), a:has-text("Delete")'
                    )
                    if not delete_btn:
                        await actions_col.click()
                        await page.wait_for_timeout(500)
                        delete_btn = await page.query_selector(
                            'a:has-text("Delete Key Pair"), '
                            'button:has-text("Delete")'
                        )
                    if delete_btn:
                        await delete_btn.click()
                        await page.wait_for_timeout(1000)
                        confirm = await page.query_selector(
                            ".modal .btn-danger, "
                            '.modal input[type="submit"]'
                        )
                        if confirm:
                            await confirm.click()
                            await page.wait_for_timeout(3000)
                            await screenshot(page, "delete_done")
                            messages_el = await page.query_selector(
                                ".messages, .alert"
                            )
                            if messages_el:
                                msg_text = await messages_el.inner_text()
                                expected = (
                                    f"Deleted Key Pair: {kp_name}"
                                )
                                if expected in msg_text:
                                    results.append(
                                        {
                                            "name": "T3_delete_message",
                                            "status": "pass",
                                            "message": msg_text.strip(),
                                        }
                                    )
                                else:
                                    results.append(
                                        {
                                            "name": "T3_delete_message",
                                            "status": "fail",
                                            "error": (
                                                f"Expected '{expected}' "
                                                f"in '{msg_text}'"
                                            ),
                                        }
                                    )
                            else:
                                results.append(
                                    {
                                        "name": "T3_delete_message",
                                        "status": "pass",
                                        "note": "No message element",
                                    }
                                )
                        else:
                            results.append(
                                {
                                    "name": "T3_delete_message",
                                    "status": "fail",
                                    "error": "No confirm button in modal",
                                }
                            )
                    else:
                        results.append(
                            {
                                "name": "T3_delete_message",
                                "status": "fail",
                                "error": "No delete button found",
                            }
                        )
                else:
                    results.append(
                        {
                            "name": "T3_delete_message",
                            "status": "fail",
                            "error": "No actions column found",
                        }
                    )
            else:
                results.append(
                    {
                        "name": "T3_delete_message",
                        "status": "skip",
                        "note": f"Keypair {kp_name} not found in table",
                    }
                )
        except Exception as e:
            await screenshot(page, "delete_fail")
            results.append(
                {
                    "name": "T3_delete_message",
                    "status": "fail",
                    "error": str(e),
                }
            )

        await browser.close()

    _write_results()
    failed = sum(1 for r in results if r["status"] == "fail")
    sys.exit(1 if failed else 0)


def _write_results():
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    with open(RESULTS_DIR / "results.json", "w") as f:
        json.dump(results, f, indent=2)
    passed = sum(1 for r in results if r["status"] == "pass")
    failed = sum(1 for r in results if r["status"] == "fail")
    skipped = sum(1 for r in results if r["status"] == "skip")
    print(f"\nPlaywright: {passed} passed, {failed} failed, {skipped} skipped")
    for r in results:
        icon = {"pass": "PASS", "fail": "FAIL", "skip": "SKIP"}.get(
            r["status"], "????"
        )
        print(f"  [{icon}] {r['name']}")


if __name__ == "__main__":
    asyncio.run(main())
